// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Sample.Api.Models;

/// <summary>
/// Test model
/// </summary>
public record TestModel
{
    /// <summary>
    /// Test ID
    /// </summary>
    [Required]
    public int Id { get; set; }

    /// <summary>
    /// Test name
    /// </summary>
    [Required]
    [StringLength(100, MinimumLength = 1)]
    public string Name { get; set; }

}
