// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Sample.Api.Controllers;

/// <summary>
/// Contrôleur pour Test
/// </summary>
[ApiController]
[Route("[controller]")]
public partial class TestController : ControllerBase
{
    /// <summary>
    /// Test endpoint
    /// </summary>
    [HttpGet("test")]
    public async Task<ActionResult<TestModel>> GetTest()
    {
        // TODO: Implémenter la logique
        await Task.CompletedTask;
        throw new NotImplementedException();
    }

}
