namespace TeknixIT.OpenApiGenerator.Server;

/// <summary>
/// Constants used throughout the generator.
/// </summary>
internal static class Constants
{
    /// <summary>
    /// Metadata keys for additional files.
    /// </summary>
    public static class MetadataKeys
    {
        public const string SourceItemType = "build_metadata.AdditionalFiles.SourceItemType";
        public const string GenerateContracts = "build_metadata.AdditionalFiles.GenerateContracts";
        public const string GenerateControllers = "build_metadata.AdditionalFiles.GenerateControllers";
        public const string UseRecords = "build_metadata.AdditionalFiles.UseRecords";
        public const string GenerateValidationAttributes = "build_metadata.AdditionalFiles.GenerateValidationAttributes";
        public const string GenerateXmlDocumentation = "build_metadata.AdditionalFiles.GenerateXmlDocumentation";
        public const string UseAsyncControllers = "build_metadata.AdditionalFiles.UseAsyncControllers";
        public const string AddApiControllerAttribute = "build_metadata.AdditionalFiles.AddApiControllerAttribute";
        public const string BaseNamespace = "build_metadata.AdditionalFiles.BaseNamespace";
        public const string ContractsNamespace = "build_metadata.AdditionalFiles.ContractsNamespace";
        public const string ControllersNamespace = "build_metadata.AdditionalFiles.ControllersNamespace";
        public const string ControllerBaseClass = "build_metadata.AdditionalFiles.ControllerBaseClass";
    }

    /// <summary>
    /// Default values for configuration.
    /// </summary>
    public static class Defaults
    {
        public const string SourceItemTypeValue = "OpenApiGenerator";
        public const string BaseNamespace = "Generated";
        public const string ContractsNamespace = "Contracts";
        public const string ControllersNamespace = "Controllers";
        public const string ControllerBaseClass = "ControllerBase";
    }

    /// <summary>
    /// Code generation constants.
    /// </summary>
    public static class CodeGeneration
    {
        public const string AutoGeneratedHeader = "// <auto-generated />";
        public const string NullableDirective = "#nullable enable";
        public const string Indent = "    ";
    }
}
