using Microsoft.CodeAnalysis;

namespace TeknixIT.OpenApiGenerator.Server.Tests;

/// <summary>
/// Tests for contract (schema, enum, model) generation from OpenAPI specifications
/// </summary>
[TestFixture]
public class ContractGenerationTests : TestBase
{
    [Test]
    public void SimpleApi_ShouldGenerateUserContract()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var userContract = GetGeneratedSource(result, "User.g.cs");

        const string expectedUserContract = """
                                            // <auto-generated />
                                            #nullable enable

                                            using System;
                                            using System.Collections.Generic;
                                            using System.ComponentModel.DataAnnotations;

                                            namespace TestApp.Contracts;

                                            public record User
                                            {
                                                [Required]
                                                public required string Id { get; set; }
                                                [Required]
                                                public required string Name { get; set; }
                                                [Required]
                                                public required string Email { get; set; }
                                            }

                                            """;

        AssertSourceEquals(userContract.SourceText.ToString(), expectedUserContract, "User.g.cs");
    }

    [Test]
    public void ComplexApi_ShouldGenerateAllSchemas()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);

        // Verify all schemas are generated
        var product = GetGeneratedSource(result, "Product.g.cs");
        var createProductRequest = GetGeneratedSource(result, "CreateProductRequest.g.cs");
        var updateProductRequest = GetGeneratedSource(result, "UpdateProductRequest.g.cs");
        var productStatus = GetGeneratedSource(result, "ProductStatus.g.cs");

        // Verify Product contract
        const string expectedProduct = """
                                       // <auto-generated />
                                       #nullable enable

                                       using System;
                                       using System.Collections.Generic;
                                       using System.ComponentModel.DataAnnotations;

                                       namespace TestApp.Contracts;

                                       public record Product
                                       {
                                           [Required]
                                           public required long Id { get; set; }
                                           [Required]
                                           [StringLength(100, MinimumLength = 1)]
                                           public required string Name { get; set; }
                                           [Required]
                                           public required string Description { get; set; }
                                           [Required]
                                           [Range(0, double.MaxValue)]
                                           public required double Price { get; set; }
                                           [Required]
                                           public required string Category { get; set; }
                                           [Required]
                                           public required ProductStatus Status { get; set; }
                                           [Required]
                                           public required ICollection<string> Tags { get; set; }
                                           [Required]
                                           public required DateTime CreatedAt { get; set; }
                                       }

                                       """;

        AssertSourceEquals(product.SourceText.ToString(), expectedProduct, "Product.g.cs");

        // Verify CreateProductRequest contract
        const string expectedCreateProductRequest = """
                                                    // <auto-generated />
                                                    #nullable enable

                                                    using System;
                                                    using System.Collections.Generic;
                                                    using System.ComponentModel.DataAnnotations;

                                                    namespace TestApp.Contracts;

                                                    public record CreateProductRequest
                                                    {
                                                        [Required]
                                                        [StringLength(100, MinimumLength = 1)]
                                                        public required string Name { get; set; }
                                                        [Required]
                                                        public required string Description { get; set; }
                                                        [Required]
                                                        [Range(0, double.MaxValue)]
                                                        public required double Price { get; set; }
                                                        [Required]
                                                        public required string Category { get; set; }
                                                        [Required]
                                                        public required ICollection<string> Tags { get; set; }
                                                    }

                                                    """;

        AssertSourceEquals(createProductRequest.SourceText.ToString(), expectedCreateProductRequest, "CreateProductRequest.g.cs");

        // Verify UpdateProductRequest contract
        const string expectedUpdateProductRequest = """
                                                    // <auto-generated />
                                                    #nullable enable

                                                    using System;
                                                    using System.Collections.Generic;
                                                    using System.ComponentModel.DataAnnotations;

                                                    namespace TestApp.Contracts;

                                                    public record UpdateProductRequest
                                                    {
                                                        [Required]
                                                        [StringLength(100, MinimumLength = 1)]
                                                        public required string Name { get; set; }
                                                        [Required]
                                                        public required string Description { get; set; }
                                                        [Required]
                                                        [Range(0, double.MaxValue)]
                                                        public required double Price { get; set; }
                                                        [Required]
                                                        public required string Category { get; set; }
                                                        [Required]
                                                        public required ProductStatus Status { get; set; }
                                                        [Required]
                                                        public required ICollection<string> Tags { get; set; }
                                                    }

                                                    """;

        AssertSourceEquals(updateProductRequest.SourceText.ToString(), expectedUpdateProductRequest, "UpdateProductRequest.g.cs");

        // ProductStatus is verified in ComplexApi_ShouldGenerateProductStatusEnum test
    }

    [Test]
    public void EnumApi_ShouldGenerateOrderStatusEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "enum-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var orderStatus = GetGeneratedSource(result, "OrderStatus.g.cs");

        const string expectedOrderStatus = """
                                           // <auto-generated />
                                           #nullable enable

                                           using System;
                                           using System.Collections.Generic;
                                           using System.ComponentModel.DataAnnotations;

                                           namespace TestApp.Contracts;

                                           public enum OrderStatus
                                           {
                                               /// <summary>
                                               /// Pending
                                               /// </summary>
                                               Pending,
                                               /// <summary>
                                               /// Processing
                                               /// </summary>
                                               Processing,
                                               /// <summary>
                                               /// Completed
                                               /// </summary>
                                               Completed,
                                               /// <summary>
                                               /// Cancelled
                                               /// </summary>
                                               Cancelled
                                           }

                                           """;

        AssertSourceEquals(orderStatus.SourceText.ToString(), expectedOrderStatus, "OrderStatus.g.cs");
    }

    [Test]
    public void EnumApi_ShouldGeneratePriorityEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "enum-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var priority = GetGeneratedSource(result, "Priority.g.cs");

        const string expectedPriority = """
                                        // <auto-generated />
                                        #nullable enable

                                        using System;
                                        using System.Collections.Generic;
                                        using System.ComponentModel.DataAnnotations;

                                        namespace TestApp.Contracts;

                                        public enum Priority
                                        {
                                            /// <summary>
                                            /// Low
                                            /// </summary>
                                            Low,
                                            /// <summary>
                                            /// Medium
                                            /// </summary>
                                            Medium,
                                            /// <summary>
                                            /// High
                                            /// </summary>
                                            High,
                                            /// <summary>
                                            /// Urgent
                                            /// </summary>
                                            Urgent
                                        }

                                        """;

        AssertSourceEquals(priority.SourceText.ToString(), expectedPriority, "Priority.g.cs");
    }

    [Test]
    public void EnumApi_ShouldGeneratePaymentMethodEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "enum-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var paymentMethod = GetGeneratedSource(result, "PaymentMethod.g.cs");

        const string expectedPaymentMethod = """
                                             // <auto-generated />
                                             #nullable enable

                                             using System;
                                             using System.Collections.Generic;
                                             using System.ComponentModel.DataAnnotations;

                                             namespace TestApp.Contracts;

                                             public enum PaymentMethod
                                             {
                                                 /// <summary>
                                                 /// CreditCard
                                                 /// </summary>
                                                 CreditCard,
                                                 /// <summary>
                                                 /// DebitCard
                                                 /// </summary>
                                                 DebitCard,
                                                 /// <summary>
                                                 /// PayPal
                                                 /// </summary>
                                                 PayPal,
                                                 /// <summary>
                                                 /// BankTransfer
                                                 /// </summary>
                                                 BankTransfer
                                             }

                                             """;

        AssertSourceEquals(paymentMethod.SourceText.ToString(), expectedPaymentMethod, "PaymentMethod.g.cs");
    }

    [Test]
    public void ComplexApi_ShouldGenerateProductStatusEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var productStatus = GetGeneratedSource(result, "ProductStatus.g.cs");

        const string expectedProductStatus = """
                                             // <auto-generated />
                                             #nullable enable

                                             using System;
                                             using System.Collections.Generic;
                                             using System.ComponentModel.DataAnnotations;

                                             namespace TestApp.Contracts;

                                             public enum ProductStatus
                                             {
                                                 /// <summary>
                                                 /// Draft
                                                 /// </summary>
                                                 Draft,
                                                 /// <summary>
                                                 /// Active
                                                 /// </summary>
                                                 Active,
                                                 /// <summary>
                                                 /// Archived
                                                 /// </summary>
                                                 Archived
                                             }

                                             """;

        AssertSourceEquals(productStatus.SourceText.ToString(), expectedProductStatus, "ProductStatus.g.cs");
    }

    [Test]
    public void NestedObjects_ShouldGenerateAllSchemas()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "nested-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);

        // Verify all schemas are generated
        var company = GetGeneratedSource(result, "Company.g.cs");
        var address = GetGeneratedSource(result, "Address.g.cs");
        var employee = GetGeneratedSource(result, "Employee.g.cs");

        // Verify Company contract
        const string expectedCompany = """
                                       // <auto-generated />
                                       #nullable enable

                                       using System;
                                       using System.Collections.Generic;
                                       using System.ComponentModel.DataAnnotations;

                                       namespace TestApp.Contracts;

                                       public record Company
                                       {
                                           [Required]
                                           public required string Name { get; set; }
                                           [Required]
                                           public required Address Address { get; set; }
                                           [Required]
                                           public required ICollection<Employee> Employees { get; set; }
                                       }

                                       """;

        AssertSourceEquals(company.SourceText.ToString(), expectedCompany, "Company.g.cs");

        // Verify Address contract
        const string expectedAddress = """
                                       // <auto-generated />
                                       #nullable enable

                                       using System;
                                       using System.Collections.Generic;
                                       using System.ComponentModel.DataAnnotations;

                                       namespace TestApp.Contracts;

                                       public record Address
                                       {
                                           [Required]
                                           public required string Street { get; set; }
                                           [Required]
                                           public required string City { get; set; }
                                           [Required]
                                           public required string ZipCode { get; set; }
                                           [Required]
                                           public required string Country { get; set; }
                                       }

                                       """;

        AssertSourceEquals(address.SourceText.ToString(), expectedAddress, "Address.g.cs");

        // Verify Employee contract
        const string expectedEmployee = """
                                        // <auto-generated />
                                        #nullable enable

                                        using System;
                                        using System.Collections.Generic;
                                        using System.ComponentModel.DataAnnotations;

                                        namespace TestApp.Contracts;

                                        public record Employee
                                        {
                                            [Required]
                                            public required string FirstName { get; set; }
                                            [Required]
                                            public required string LastName { get; set; }
                                            [Required]
                                            public required string Position { get; set; }
                                            [Required]
                                            public required double Salary { get; set; }
                                        }

                                        """;

        AssertSourceEquals(employee.SourceText.ToString(), expectedEmployee, "Employee.g.cs");
    }

    [Test]
    public void NestedObjects_ShouldReferenceNestedTypes()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "nested-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var company = GetGeneratedSource(result, "Company.g.cs");

        const string expectedCompany = """
                                       // <auto-generated />
                                       #nullable enable

                                       using System;
                                       using System.Collections.Generic;
                                       using System.ComponentModel.DataAnnotations;

                                       namespace TestApp.Contracts;

                                       public record Company
                                       {
                                           [Required]
                                           public required string Name { get; set; }
                                           [Required]
                                           public required Address Address { get; set; }
                                           [Required]
                                           public required ICollection<Employee> Employees { get; set; }
                                       }

                                       """;

        AssertSourceEquals(company.SourceText.ToString(), expectedCompany, "Company.g.cs");
    }

    [Test]
    public void Product_ShouldHaveRequiredAndOptionalProperties()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var product = GetGeneratedSource(result, "Product.g.cs");

        const string expectedProduct = """
                                       // <auto-generated />
                                       #nullable enable

                                       using System;
                                       using System.Collections.Generic;
                                       using System.ComponentModel.DataAnnotations;

                                       namespace TestApp.Contracts;

                                       public record Product
                                       {
                                           [Required]
                                           public required long Id { get; set; }
                                           [Required]
                                           [StringLength(100, MinimumLength = 1)]
                                           public required string Name { get; set; }
                                           [Required]
                                           public required string Description { get; set; }
                                           [Required]
                                           [Range(0, double.MaxValue)]
                                           public required double Price { get; set; }
                                           [Required]
                                           public required string Category { get; set; }
                                           [Required]
                                           public required ProductStatus Status { get; set; }
                                           [Required]
                                           public required ICollection<string> Tags { get; set; }
                                           [Required]
                                           public required DateTime CreatedAt { get; set; }
                                       }

                                       """;

        AssertSourceEquals(product.SourceText.ToString(), expectedProduct, "Product.g.cs");
    }

    [Test]
    public void Product_ShouldUseCorrectDataTypes()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var product = GetGeneratedSource(result, "Product.g.cs");

        const string expectedProduct = """
                                       // <auto-generated />
                                       #nullable enable

                                       using System;
                                       using System.Collections.Generic;
                                       using System.ComponentModel.DataAnnotations;

                                       namespace TestApp.Contracts;

                                       public record Product
                                       {
                                           [Required]
                                           public required long Id { get; set; }
                                           [Required]
                                           [StringLength(100, MinimumLength = 1)]
                                           public required string Name { get; set; }
                                           [Required]
                                           public required string Description { get; set; }
                                           [Required]
                                           [Range(0, double.MaxValue)]
                                           public required double Price { get; set; }
                                           [Required]
                                           public required string Category { get; set; }
                                           [Required]
                                           public required ProductStatus Status { get; set; }
                                           [Required]
                                           public required ICollection<string> Tags { get; set; }
                                           [Required]
                                           public required DateTime CreatedAt { get; set; }
                                       }

                                       """;

        AssertSourceEquals(product.SourceText.ToString(), expectedProduct, "Product.g.cs");
    }

    [Test]
    public void EmptyApi_ShouldNotGenerateFiles()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "empty-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result, "No errors should be generated even for an empty API");
        Assert.That(result.GeneratedSources, Is.Empty,
            "No files should be generated for an empty API");
    }
}
