using Microsoft.CodeAnalysis;

namespace TeknixIT.OpenApiGenerator.Server.Tests;

/// <summary>
/// Tests for controller generation from OpenAPI specifications
/// </summary>
[TestFixture]
public class ControllerGenerationTests : TestBase
{
    [Test]
    public void SimpleApi_ShouldGenerateUsersController()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var usersController = GetGeneratedSource(result, "UsersController.g.cs");

        const string expectedUsersController = """
                                               // <auto-generated />
                                               #nullable enable

                                               using System;
                                               using System.Collections.Generic;
                                               using System.Threading.Tasks;
                                               using Microsoft.AspNetCore.Mvc;
                                               using TestApp.Contracts;

                                               namespace TestApp.Controllers;

                                               /// <summary>
                                               /// Controller for Users
                                               /// </summary>
                                               [ApiController]
                                               [Route("/users")]
                                               public abstract class UsersControllerBase : ControllerBase
                                               {
                                                   /// <summary>
                                                   /// No description available.
                                                   /// </summary>
                                                   /// <param name="id"></param>
                                                   [HttpGet("{id}")]
                                                   public abstract Task<IActionResult> GetUser([FromRoute] string id);

                                               }

                                               """;

        AssertSourceEquals(usersController.SourceText.ToString(), expectedUsersController, "UsersController.g.cs");
    }

    [Test]
    public void ComplexApi_ShouldGenerateProductsController()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        Assert.That(result.GeneratedSources.Any(s => s.HintName == "ProductsController.g.cs"), Is.True,
            "ProductsController should be generated");
    }

    [Test]
    public void ComplexApi_ShouldGenerateAllHttpMethods()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "ProductsController.g.cs");
        var sourceText = controller.SourceText.ToString();

        AssertContainsLine(sourceText, "[HttpGet]");
        AssertLineAfter(sourceText, "[HttpGet]", "public abstract Task<IActionResult> ListProducts");
        AssertContainsLine(sourceText, "[HttpPost]");
        AssertLineAfter(sourceText, "[HttpPost]", "public abstract Task<IActionResult> CreateProduct");
        AssertContainsLine(sourceText, "[HttpPut");
        AssertContainsLine(sourceText, "[HttpDelete");
    }

    [Test]
    public void ComplexApi_ShouldHandleVariousParameterTypes()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "ProductsController.g.cs");
        var sourceText = controller.SourceText.ToString();

        AssertContainsLine(sourceText, "public abstract Task<IActionResult> ListProducts([FromQuery] string category, [FromQuery] double minPrice");
        AssertContainsLine(sourceText, "long id"); // path param long in different method
    }

    [Test]
    public void Controller_WithAsyncEnabled_ShouldGenerateAsyncMethods()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.UseAsyncControllers"] = "true";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");
        AssertContainsLine(controller.SourceText.ToString(), "Task<IActionResult>");
    }

    [Test]
    public void Controller_WithAsyncDisabled_ShouldGenerateSyncMethods()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.UseAsyncControllers"] = "false";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");
        var sourceText = controller.SourceText.ToString();
        AssertContainsLine(sourceText, "IActionResult GetUser(");
    }

    [Test]
    public void Controller_WithApiControllerAttribute_ShouldAddAttribute()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.AddApiControllerAttribute"] = "true";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");
        AssertContainsLine(controller.SourceText.ToString(), "[ApiController]");
    }

    [Test]
    public void Controller_WithoutApiControllerAttribute_ShouldNotAddAttribute()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.AddApiControllerAttribute"] = "false";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");
        var sourceText = controller.SourceText.ToString();
        Assert.That(sourceText.Trim().Replace(" ", "").Contains("[ApiController]"), Is.False,
            "[ApiController] attribute should not be present");
    }

    [Test]
    public void Controller_WithCustomBaseClass_ShouldInheritFromCustomClass()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.ControllerBaseClass"] = "MyApp.Controllers.BaseApiController";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");
        AssertContainsLine(controller.SourceText.ToString(), ": BaseApiController");
    }
}
