using Microsoft.CodeAnalysis;

namespace TeknixIT.OpenApiGenerator.Server.Tests;

/// <summary>
/// Tests for contract (schema, enum, model) generation from OpenAPI specifications
/// </summary>
[TestFixture]
public class ContractGenerationTests : TestBase
{
    [Test]
    public void SimpleApi_ShouldGenerateUserContract()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var userContract = GetGeneratedSource(result, "User.g.cs");

        const string expectedUserContract = """
                                            // <auto-generated />
                                            #nullable enable

                                            using System;
                                            using System.Collections.Generic;
                                            using System.ComponentModel.DataAnnotations;

                                            namespace TestApp.Contracts;

                                            public record User
                                            {
                                                [Required]
                                                public required string Id { get; set; }
                                                [Required]
                                                public required string Name { get; set; }
                                                [Required]
                                                public required string Email { get; set; }
                                            }

                                            """;

        AssertSourceEquals(userContract.SourceText.ToString(), expectedUserContract, "User.g.cs");
    }

    [Test]
    public void ComplexApi_ShouldGenerateAllSchemas()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.GeneratedSources.Any(s => s.HintName == "Product.g.cs"), Is.True,
                    "Product contract should be generated");
            Assert.That(result.GeneratedSources.Any(s => s.HintName == "CreateProductRequest.g.cs"), Is.True,
                "CreateProductRequest contract should be generated");
            Assert.That(result.GeneratedSources.Any(s => s.HintName == "UpdateProductRequest.g.cs"), Is.True,
                "UpdateProductRequest contract should be generated");
            Assert.That(result.GeneratedSources.Any(s => s.HintName == "ProductStatus.g.cs"), Is.True,
                "ProductStatus enum should be generated");
        }
    }

    [Test]
    public void EnumApi_ShouldGenerateOrderStatusEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "enum-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var orderStatus = GetGeneratedSource(result, "OrderStatus.g.cs");

        const string expectedOrderStatus = """
                                           // <auto-generated />
                                           #nullable enable

                                           using System;
                                           using System.Collections.Generic;
                                           using System.ComponentModel.DataAnnotations;

                                           namespace TestApp.Contracts;

                                           public enum OrderStatus
                                           {
                                               /// <summary>
                                               /// Pending
                                               /// </summary>
                                               Pending,
                                               /// <summary>
                                               /// Processing
                                               /// </summary>
                                               Processing,
                                               /// <summary>
                                               /// Completed
                                               /// </summary>
                                               Completed,
                                               /// <summary>
                                               /// Cancelled
                                               /// </summary>
                                               Cancelled
                                           }

                                           """;

        AssertSourceEquals(orderStatus.SourceText.ToString(), expectedOrderStatus, "OrderStatus.g.cs");
    }

    [Test]
    public void EnumApi_ShouldGeneratePriorityEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "enum-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var priority = GetGeneratedSource(result, "Priority.g.cs");

        const string expectedPriority = """
                                        // <auto-generated />
                                        #nullable enable

                                        using System;
                                        using System.Collections.Generic;
                                        using System.ComponentModel.DataAnnotations;

                                        namespace TestApp.Contracts;

                                        public enum Priority
                                        {
                                            /// <summary>
                                            /// Low
                                            /// </summary>
                                            Low,
                                            /// <summary>
                                            /// Medium
                                            /// </summary>
                                            Medium,
                                            /// <summary>
                                            /// High
                                            /// </summary>
                                            High,
                                            /// <summary>
                                            /// Urgent
                                            /// </summary>
                                            Urgent
                                        }

                                        """;

        AssertSourceEquals(priority.SourceText.ToString(), expectedPriority, "Priority.g.cs");
    }

    [Test]
    public void EnumApi_ShouldGeneratePaymentMethodEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "enum-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var paymentMethod = GetGeneratedSource(result, "PaymentMethod.g.cs");

        const string expectedPaymentMethod = """
                                             // <auto-generated />
                                             #nullable enable

                                             using System;
                                             using System.Collections.Generic;
                                             using System.ComponentModel.DataAnnotations;

                                             namespace TestApp.Contracts;

                                             public enum PaymentMethod
                                             {
                                                 /// <summary>
                                                 /// CreditCard
                                                 /// </summary>
                                                 CreditCard,
                                                 /// <summary>
                                                 /// DebitCard
                                                 /// </summary>
                                                 DebitCard,
                                                 /// <summary>
                                                 /// PayPal
                                                 /// </summary>
                                                 PayPal,
                                                 /// <summary>
                                                 /// BankTransfer
                                                 /// </summary>
                                                 BankTransfer
                                             }

                                             """;

        AssertSourceEquals(paymentMethod.SourceText.ToString(), expectedPaymentMethod, "PaymentMethod.g.cs");
    }

    [Test]
    public void ComplexApi_ShouldGenerateProductStatusEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var productStatus = GetGeneratedSource(result, "ProductStatus.g.cs");

        const string expectedProductStatus = """
                                             // <auto-generated />
                                             #nullable enable

                                             using System;
                                             using System.Collections.Generic;
                                             using System.ComponentModel.DataAnnotations;

                                             namespace TestApp.Contracts;

                                             public enum ProductStatus
                                             {
                                                 /// <summary>
                                                 /// Draft
                                                 /// </summary>
                                                 Draft,
                                                 /// <summary>
                                                 /// Active
                                                 /// </summary>
                                                 Active,
                                                 /// <summary>
                                                 /// Archived
                                                 /// </summary>
                                                 Archived
                                             }

                                             """;

        AssertSourceEquals(productStatus.SourceText.ToString(), expectedProductStatus, "ProductStatus.g.cs");
    }

    [Test]
    public void NestedObjects_ShouldGenerateAllSchemas()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "nested-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);

        using (Assert.EnterMultipleScope())
        {
            Assert.That(result.GeneratedSources.Any(s => s.HintName == "Company.g.cs"), Is.True,
                    "Company contract should be generated");
            Assert.That(result.GeneratedSources.Any(s => s.HintName == "Address.g.cs"), Is.True,
                "Address contract should be generated");
            Assert.That(result.GeneratedSources.Any(s => s.HintName == "Employee.g.cs"), Is.True,
                "Employee contract should be generated");
        }
    }

    [Test]
    public void NestedObjects_ShouldReferenceNestedTypes()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "nested-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var company = GetGeneratedSource(result, "Company.g.cs");

        AssertContainsLinesInOrder(company.SourceText.ToString(),
            "public record Company",
            "public required string Name { get; set; }",
            "public required Address Address { get; set; }",
            "public required ICollection<Employee> Employees { get; set; }"
        );
    }

    [Test]
    public void Product_ShouldHaveRequiredAndOptionalProperties()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var product = GetGeneratedSource(result, "Product.g.cs");
        var sourceText = product.SourceText.ToString();

        AssertContainsLinesInOrder(sourceText,
            "public record Product",
            "public required long Id { get; set; }",
            "public required string Name { get; set; }",
            "public required string Description { get; set; }",
            "public required double Price { get; set; }",
            "public required string Category { get; set; }",
            "public required ProductStatus Status { get; set; }"
        );
    }

    [Test]
    public void Product_ShouldUseCorrectDataTypes()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var product = GetGeneratedSource(result, "Product.g.cs");
        var sourceText = product.SourceText.ToString();

        AssertContainsLinesInOrder(sourceText,
            "public record Product",
            "long Id", // integer format int64 -> long
            "string Name", // string -> string
            "double Price", // number format double -> double
            "ProductStatus Status", // enum reference
            "ICollection<string>", // array -> ICollection
            "DateTime" // date-time -> DateTime
        );
    }

    [Test]
    public void EmptyApi_ShouldNotGenerateFiles()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "empty-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result, "No errors should be generated even for an empty API");
        Assert.That(result.GeneratedSources, Is.Empty,
            "No files should be generated for an empty API");
    }
}
