using Microsoft.CodeAnalysis;

namespace TeknixIT.OpenApiGenerator.Server.Tests;

/// <summary>
/// Tests for controller generation from OpenAPI specifications
/// </summary>
[TestFixture]
public class ControllerGenerationTests : TestBase
{
    [Test]
    public void SimpleApi_ShouldGenerateUsersController()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var usersController = GetGeneratedSource(result, "UsersController.g.cs");

        const string expectedUsersController = """
                                               // <auto-generated />
                                               #nullable enable

                                               using System;
                                               using System.Collections.Generic;
                                               using System.Threading.Tasks;
                                               using Microsoft.AspNetCore.Mvc;
                                               using TestApp.Contracts;

                                               namespace TestApp.Controllers;

                                               /// <summary>
                                               /// Controller for Users
                                               /// </summary>
                                               [ApiController]
                                               [Route("/users")]
                                               public abstract class UsersControllerBase : ControllerBase
                                               {
                                                   /// <summary>
                                                   /// No description available.
                                                   /// </summary>
                                                   /// <param name="id"></param>
                                                   [HttpGet("{id}")]
                                                   public abstract Task<IActionResult> GetUser([FromRoute] string id);

                                               }

                                               """;

        AssertSourceEquals(usersController.SourceText.ToString(), expectedUsersController, "UsersController.g.cs");
    }

    [Test]
    public void ComplexApi_ShouldGenerateProductsController()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var productsController = GetGeneratedSource(result, "ProductsController.g.cs");

        const string expectedProductsController = """
                                                   // <auto-generated />
                                                   #nullable enable

                                                   using System;
                                                   using System.Collections.Generic;
                                                   using System.Threading.Tasks;
                                                   using Microsoft.AspNetCore.Mvc;
                                                   using TestApp.Contracts;

                                                   namespace TestApp.Controllers;

                                                   /// <summary>
                                                   /// Controller for Products
                                                   /// </summary>
                                                   [ApiController]
                                                   [Route("/products")]
                                                   public abstract class ProductsControllerBase : ControllerBase
                                                   {
                                                       /// <summary>
                                                       /// No description available.
                                                       /// </summary>
                                                       /// <param name="category"></param>
                                                       /// <param name="minPrice"></param>
                                                       /// <param name="maxPrice"></param>
                                                       /// <param name="inStock"></param>
                                                       [HttpGet]
                                                       public abstract Task<IActionResult> ListProducts([FromQuery] string category, [FromQuery] double minPrice, [FromQuery] double maxPrice, [FromQuery] bool inStock);

                                                       /// <summary>
                                                       /// No description available.
                                                       /// </summary>
                                                       /// <param name="request"></param>
                                                       [HttpPost]
                                                       public abstract Task<IActionResult> CreateProduct([FromBody] CreateProductRequest request);

                                                       /// <summary>
                                                       /// No description available.
                                                       /// </summary>
                                                       /// <param name="id"></param>
                                                       [HttpGet("{id}")]
                                                       public abstract Task<IActionResult> GetProduct([FromRoute] long id);

                                                       /// <summary>
                                                       /// No description available.
                                                       /// </summary>
                                                       /// <param name="id"></param>
                                                       /// <param name="request"></param>
                                                       [HttpPut("{id}")]
                                                       public abstract Task<IActionResult> UpdateProduct([FromRoute] long id, [FromBody] UpdateProductRequest request);

                                                       /// <summary>
                                                       /// No description available.
                                                       /// </summary>
                                                       /// <param name="id"></param>
                                                       [HttpDelete("{id}")]
                                                       public abstract Task<IActionResult> DeleteProduct([FromRoute] long id);

                                                   }

                                                   """;

        AssertSourceEquals(productsController.SourceText.ToString(), expectedProductsController, "ProductsController.g.cs");
    }

    [Test]
    public void ComplexApi_ShouldGenerateAllHttpMethods()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "ProductsController.g.cs");

        const string expectedController = """
                                          // <auto-generated />
                                          #nullable enable

                                          using System;
                                          using System.Collections.Generic;
                                          using System.Threading.Tasks;
                                          using Microsoft.AspNetCore.Mvc;
                                          using TestApp.Contracts;

                                          namespace TestApp.Controllers;

                                          /// <summary>
                                          /// Controller for Products
                                          /// </summary>
                                          [ApiController]
                                          [Route("/products")]
                                          public abstract class ProductsControllerBase : ControllerBase
                                          {
                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="category"></param>
                                              /// <param name="minPrice"></param>
                                              /// <param name="maxPrice"></param>
                                              /// <param name="inStock"></param>
                                              [HttpGet]
                                              public abstract Task<IActionResult> ListProducts([FromQuery] string category, [FromQuery] double minPrice, [FromQuery] double maxPrice, [FromQuery] bool inStock);

                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="request"></param>
                                              [HttpPost]
                                              public abstract Task<IActionResult> CreateProduct([FromBody] CreateProductRequest request);

                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              [HttpGet("{id}")]
                                              public abstract Task<IActionResult> GetProduct([FromRoute] long id);

                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              /// <param name="request"></param>
                                              [HttpPut("{id}")]
                                              public abstract Task<IActionResult> UpdateProduct([FromRoute] long id, [FromBody] UpdateProductRequest request);

                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              [HttpDelete("{id}")]
                                              public abstract Task<IActionResult> DeleteProduct([FromRoute] long id);

                                          }

                                          """;

        AssertSourceEquals(controller.SourceText.ToString(), expectedController, "ProductsController.g.cs");
    }

    [Test]
    public void ComplexApi_ShouldHandleVariousParameterTypes()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "complex-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "ProductsController.g.cs");

        const string expectedController = """
                                          // <auto-generated />
                                          #nullable enable

                                          using System;
                                          using System.Collections.Generic;
                                          using System.Threading.Tasks;
                                          using Microsoft.AspNetCore.Mvc;
                                          using TestApp.Contracts;

                                          namespace TestApp.Controllers;

                                          /// <summary>
                                          /// Controller for Products
                                          /// </summary>
                                          [ApiController]
                                          [Route("/products")]
                                          public abstract class ProductsControllerBase : ControllerBase
                                          {
                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="category"></param>
                                              /// <param name="minPrice"></param>
                                              /// <param name="maxPrice"></param>
                                              /// <param name="inStock"></param>
                                              [HttpGet]
                                              public abstract Task<IActionResult> ListProducts([FromQuery] string category, [FromQuery] double minPrice, [FromQuery] double maxPrice, [FromQuery] bool inStock);

                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="request"></param>
                                              [HttpPost]
                                              public abstract Task<IActionResult> CreateProduct([FromBody] CreateProductRequest request);

                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              [HttpGet("{id}")]
                                              public abstract Task<IActionResult> GetProduct([FromRoute] long id);

                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              /// <param name="request"></param>
                                              [HttpPut("{id}")]
                                              public abstract Task<IActionResult> UpdateProduct([FromRoute] long id, [FromBody] UpdateProductRequest request);

                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              [HttpDelete("{id}")]
                                              public abstract Task<IActionResult> DeleteProduct([FromRoute] long id);

                                          }

                                          """;

        AssertSourceEquals(controller.SourceText.ToString(), expectedController, "ProductsController.g.cs");
    }

    [Test]
    public void Controller_WithAsyncEnabled_ShouldGenerateAsyncMethods()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.UseAsyncControllers"] = "true";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");

        const string expectedController = """
                                          // <auto-generated />
                                          #nullable enable

                                          using System;
                                          using System.Collections.Generic;
                                          using System.Threading.Tasks;
                                          using Microsoft.AspNetCore.Mvc;
                                          using TestApp.Contracts;

                                          namespace TestApp.Controllers;

                                          /// <summary>
                                          /// Controller for Users
                                          /// </summary>
                                          [ApiController]
                                          [Route("/users")]
                                          public abstract class UsersControllerBase : ControllerBase
                                          {
                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              [HttpGet("{id}")]
                                              public abstract Task<IActionResult> GetUser([FromRoute] string id);

                                          }

                                          """;

        AssertSourceEquals(controller.SourceText.ToString(), expectedController, "UsersController.g.cs");
    }

    [Test]
    public void Controller_WithAsyncDisabled_ShouldGenerateSyncMethods()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.UseAsyncControllers"] = "false";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");

        const string expectedController = """
                                          // <auto-generated />
                                          #nullable enable

                                          using System;
                                          using System.Collections.Generic;
                                          using System.Threading.Tasks;
                                          using Microsoft.AspNetCore.Mvc;
                                          using TestApp.Contracts;

                                          namespace TestApp.Controllers;

                                          /// <summary>
                                          /// Controller for Users
                                          /// </summary>
                                          [ApiController]
                                          [Route("/users")]
                                          public abstract class UsersControllerBase : ControllerBase
                                          {
                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              [HttpGet("{id}")]
                                              public abstract IActionResult GetUser([FromRoute] string id);

                                          }

                                          """;

        AssertSourceEquals(controller.SourceText.ToString(), expectedController, "UsersController.g.cs");
    }

    [Test]
    public void Controller_WithApiControllerAttribute_ShouldAddAttribute()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.AddApiControllerAttribute"] = "true";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");

        const string expectedController = """
                                          // <auto-generated />
                                          #nullable enable

                                          using System;
                                          using System.Collections.Generic;
                                          using System.Threading.Tasks;
                                          using Microsoft.AspNetCore.Mvc;
                                          using TestApp.Contracts;

                                          namespace TestApp.Controllers;

                                          /// <summary>
                                          /// Controller for Users
                                          /// </summary>
                                          [ApiController]
                                          [Route("/users")]
                                          public abstract class UsersControllerBase : ControllerBase
                                          {
                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              [HttpGet("{id}")]
                                              public abstract Task<IActionResult> GetUser([FromRoute] string id);

                                          }

                                          """;

        AssertSourceEquals(controller.SourceText.ToString(), expectedController, "UsersController.g.cs");
    }

    [Test]
    public void Controller_WithoutApiControllerAttribute_ShouldNotAddAttribute()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.AddApiControllerAttribute"] = "false";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");

        const string expectedController = """
                                          // <auto-generated />
                                          #nullable enable

                                          using System;
                                          using System.Collections.Generic;
                                          using System.Threading.Tasks;
                                          using Microsoft.AspNetCore.Mvc;
                                          using TestApp.Contracts;

                                          namespace TestApp.Controllers;

                                          /// <summary>
                                          /// Controller for Users
                                          /// </summary>
                                          [Route("/users")]
                                          public abstract class UsersControllerBase : ControllerBase
                                          {
                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              [HttpGet("{id}")]
                                              public abstract Task<IActionResult> GetUser([FromRoute] string id);

                                          }

                                          """;

        AssertSourceEquals(controller.SourceText.ToString(), expectedController, "UsersController.g.cs");
    }

    [Test]
    public void Controller_WithCustomBaseClass_ShouldInheritFromCustomClass()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.ControllerBaseClass"] = "MyApp.Controllers.BaseApiController";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");

        const string expectedController = """
                                          // <auto-generated />
                                          #nullable enable

                                          using System;
                                          using System.Collections.Generic;
                                          using System.Threading.Tasks;
                                          using Microsoft.AspNetCore.Mvc;
                                          using TestApp.Contracts;
                                          using MyApp.Controllers;

                                          namespace TestApp.Controllers;

                                          /// <summary>
                                          /// Controller for Users
                                          /// </summary>
                                          [ApiController]
                                          [Route("/users")]
                                          public abstract class UsersControllerBase : BaseApiController
                                          {
                                              /// <summary>
                                              /// No description available.
                                              /// </summary>
                                              /// <param name="id"></param>
                                              [HttpGet("{id}")]
                                              public abstract Task<IActionResult> GetUser([FromRoute] string id);

                                          }

                                          """;

        AssertSourceEquals(controller.SourceText.ToString(), expectedController, "UsersController.g.cs");
    }

}
