namespace TeknixIT.OpenApiGenerator.Server.Tests;

/// <summary>
/// Tests for OpenAPI specifications in JSON format
/// </summary>
[TestFixture]
public class JsonFormatTests : TestBase
{
    [Test]
    public void JsonFormat_SimpleApi_ShouldGenerateUserContract()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.json");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var userContract = GetGeneratedSource(result, "User.g.cs");

        const string expectedUserContract = """
                                            // <auto-generated />
                                            #nullable enable

                                            using System;
                                            using System.Collections.Generic;
                                            using System.ComponentModel.DataAnnotations;

                                            namespace TestApp.Contracts;

                                            public record User
                                            {
                                                [Required]
                                                public required string Id { get; set; }
                                                [Required]
                                                public required string Name { get; set; }
                                                [Required]
                                                public required string Email { get; set; }
                                            }

                                            """;

        AssertSourceEquals(userContract.SourceText.ToString(), expectedUserContract, "User.g.cs");
    }

    [Test]
    public void JsonFormat_SimpleApi_ShouldGenerateController()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.json");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "UsersController.g.cs");

        var controllerText = controller.SourceText.ToString();
        Assert.That(controllerText, Does.Contain("UsersControllerBase"));
        Assert.That(controllerText, Does.Contain("GetUser"));
        Assert.That(controllerText, Does.Contain("Task<IActionResult>"));
        Assert.That(controllerText, Does.Contain("[HttpGet(\"{id}\")]"));
    }

    [Test]
    public void JsonFormat_EnumApi_ShouldGenerateEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "enum-api.json");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var orderStatusEnum = GetGeneratedSource(result, "OrderStatus.g.cs");

        var enumText = orderStatusEnum.SourceText.ToString();
        Assert.That(enumText, Does.Contain("public enum OrderStatus"));
        Assert.That(enumText, Does.Contain("Pending"));
        Assert.That(enumText, Does.Contain("Processing"));
        Assert.That(enumText, Does.Contain("Completed"));
        Assert.That(enumText, Does.Contain("Cancelled"));
    }

    [Test]
    public void JsonFormat_EnumApi_ShouldGenerateContractWithEnum()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "enum-api.json");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var orderContract = GetGeneratedSource(result, "Order.g.cs");

        var orderText = orderContract.SourceText.ToString();
        Assert.That(orderText, Does.Contain("public record Order"));
        Assert.That(orderText, Does.Contain("public required string Id { get; set; }"));
        Assert.That(orderText, Does.Contain("public required OrderStatus Status { get; set; }"));
    }

    [Test]
    public void JsonFormat_NestedApi_ShouldGenerateNestedContracts()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "nested-api.json");
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);

        var productContract = GetGeneratedSource(result, "Product.g.cs");
        var categoryContract = GetGeneratedSource(result, "Category.g.cs");

        // Verify Product contract
        var productText = productContract.SourceText.ToString();
        Assert.That(productText, Does.Contain("public record Product"));
        Assert.That(productText, Does.Contain("public required Category Category { get; set; }"));

        // Verify Category contract with self-reference
        var categoryText = categoryContract.SourceText.ToString();
        Assert.That(categoryText, Does.Contain("public record Category"));
        Assert.That(categoryText, Does.Contain("public required Category Parent { get; set; }"));
    }

    [Test]
    public void JsonFormat_WithCustomNamespace_ShouldUseCorrectNamespaces()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.json");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.BaseNamespace"] = "MyApp";
        config["build_metadata.AdditionalFiles.ContractsNamespace"] = "Models";
        config["build_metadata.AdditionalFiles.ControllersNamespace"] = "Api";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);

        var userContract = GetGeneratedSource(result, "User.g.cs");
        var userText = userContract.SourceText.ToString();
        Assert.That(userText, Does.Contain("namespace MyApp.Models;"));

        var controller = GetGeneratedSource(result, "UsersController.g.cs");
        var controllerText = controller.SourceText.ToString();
        Assert.That(controllerText, Does.Contain("namespace MyApp.Api;"));
        Assert.That(controllerText, Does.Contain("using MyApp.Models;"));
    }

    [Test]
    public void JsonFormat_WithoutControllers_ShouldOnlyGenerateContracts()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.json");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.GenerateControllers"] = "false";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);

        // User contract should be generated
        var userContract = GetGeneratedSource(result, "User.g.cs");

        // Controller should not be generated
        Assert.Throws<AssertionException>(() => GetGeneratedSource(result, "UsersController.g.cs"));
    }

    [Test]
    public void JsonFormat_WithoutValidationAttributes_ShouldNotIncludeRequired()
    {
        // Arrange
        var openApiFile = Path.Combine(TestDataDirectory, "simple-api.json");
        var config = CreateDefaultConfiguration();
        config["build_metadata.AdditionalFiles.GenerateValidationAttributes"] = "false";

        // Act
        var result = RunGenerator(openApiFile, config);

        // Assert
        AssertNoErrors(result);

        var userContract = GetGeneratedSource(result, "User.g.cs");
        var userText = userContract.SourceText.ToString();
        Assert.That(userText, Does.Not.Contain("[Required]"));
    }

    [Test]
    public void JsonFormat_CompareWithYaml_ShouldGenerateSameOutput()
    {
        // Arrange
        var jsonFile = Path.Combine(TestDataDirectory, "simple-api.json");
        var yamlFile = Path.Combine(TestDataDirectory, "simple-api.yaml");
        var config = CreateDefaultConfiguration();

        // Act
        var jsonResult = RunGenerator(jsonFile, config);
        var yamlResult = RunGenerator(yamlFile, config);

        // Assert
        AssertNoErrors(jsonResult);
        AssertNoErrors(yamlResult);

        var jsonUserContract = GetGeneratedSource(jsonResult, "User.g.cs");
        var yamlUserContract = GetGeneratedSource(yamlResult, "User.g.cs");

        // Both formats should produce identical output
        AssertSourceEquals(
            jsonUserContract.SourceText.ToString(),
            yamlUserContract.SourceText.ToString(),
            "JSON and YAML should produce identical contracts");
    }
}
