namespace TeknixIT.OpenApiGenerator.Server.Tests;

/// <summary>
/// Tests for path-level parameter inheritance in generated controllers.
/// Parameters defined under a path item (not under individual operations) must be
/// included in every operation's method signature.
/// </summary>
[TestFixture]
public class PathLevelParametersTests : TestBase
{
    private string _openApiFile = string.Empty;

    [SetUp]
    public void Setup()
    {
        _openApiFile = Path.Combine(TestDataDirectory, "path-level-parameters-api.yaml");
    }

    [Test]
    public void PathLevelParameter_ShouldBeIncludedInGetMethod()
    {
        // Arrange
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(_openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "BrandsController.g.cs");
        var source = controller.SourceText.ToString();

        AssertContainsLine(source, "[HttpGet(\"{brandId}\")]");
        AssertContainsLine(source, "public abstract Task<IActionResult> GetBrand([FromRoute] Guid brandId);");
    }

    [Test]
    public void PathLevelParameter_ShouldBeIncludedInPutMethod()
    {
        // Arrange
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(_openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "BrandsController.g.cs");
        var source = controller.SourceText.ToString();

        AssertContainsLine(source, "[HttpPut(\"{brandId}\")]");
        AssertContainsLine(source, "public abstract Task<IActionResult> UpdateBrand([FromRoute] Guid brandId, [FromBody] UpdateBrandRequest request);");
    }

    [Test]
    public void PathLevelParameter_ShouldNotBeDuplicated_WhenOperationAlsoDefinesIt()
    {
        // The getBrandItems operation defines a query parameter "page" at the operation level,
        // while brandId is defined at the path level. Both must appear, but brandId only once.
        var config = CreateDefaultConfiguration();

        var result = RunGenerator(_openApiFile, config);

        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "BrandsController.g.cs");
        var source = controller.SourceText.ToString();

        AssertContainsLine(source, "public abstract Task<IActionResult> GetBrandItems([FromRoute] Guid brandId, [FromQuery] int? page);");

        // brandId must appear exactly once in the getBrandItems signature
        var getBrandItemsLine = source
            .Split('\n')
            .Select(l => l.TrimStart())
            .FirstOrDefault(l => l.Contains("GetBrandItems("));

        Assert.That(getBrandItemsLine, Is.Not.Null, "GetBrandItems method not found");

        var occurrences = 0;
        var idx = 0;
        while ((idx = getBrandItemsLine!.IndexOf("brandId", idx, StringComparison.Ordinal)) != -1)
        {
            occurrences++;
            idx++;
        }
        Assert.That(occurrences, Is.EqualTo(1), $"brandId should appear exactly once in the signature, found {occurrences}:\n{getBrandItemsLine}");
    }

    [Test]
    public void PathLevelParameter_FullControllerOutput_ShouldMatchExpected()
    {
        // Arrange
        var config = CreateDefaultConfiguration();

        // Act
        var result = RunGenerator(_openApiFile, config);

        // Assert
        AssertNoErrors(result);
        var controller = GetGeneratedSource(result, "BrandsController.g.cs");

        const string expectedController = """
                                          // <auto-generated />
                                          #nullable enable

                                          using System;
                                          using System.CodeDom.Compiler;
                                          using System.Collections.Generic;
                                          using System.Threading.Tasks;
                                          using Microsoft.AspNetCore.Mvc;
                                          using TestApp.Contracts;

                                          namespace TestApp.Controllers;

                                          /// <summary>
                                          /// Controller for Brands
                                          /// </summary>
                                          [GeneratedCode("TeknixIT.OpenApiGenerator.Server", "1.0.0")]
                                          [ApiController]
                                          [Route("/brands")]
                                          public abstract class BrandsControllerBase : ControllerBase
                                          {
                                              /// <summary>
                                              /// Get a brand
                                              /// </summary>
                                              /// <param name="brandId">Unique identifier of the brand.</param>
                                              [HttpGet("{brandId}")]
                                              public abstract Task<IActionResult> GetBrand([FromRoute] Guid brandId);

                                              /// <summary>
                                              /// Update a brand
                                              /// </summary>
                                              /// <param name="brandId">Unique identifier of the brand.</param>
                                              /// <param name="request"></param>
                                              [HttpPut("{brandId}")]
                                              public abstract Task<IActionResult> UpdateBrand([FromRoute] Guid brandId, [FromBody] UpdateBrandRequest request);

                                              /// <summary>
                                              /// Get brand items
                                              /// </summary>
                                              /// <param name="brandId">Unique identifier of the brand.</param>
                                              /// <param name="page">Page number.</param>
                                              [HttpGet("{brandId}/items")]
                                              public abstract Task<IActionResult> GetBrandItems([FromRoute] Guid brandId, [FromQuery] int? page);

                                          }

                                          """;

        AssertSourceEquals(controller.SourceText.ToString(), expectedController, "BrandsController.g.cs");
    }
}