using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.OpenApi;

namespace TeknixIT.OpenApiGenerator.Server.Contracts;

/// <summary>
/// Generates C# Contracts from OpenAPI schema definitions.
/// </summary>
internal sealed class ContractGenerator
{
    private readonly GeneratorConfiguration _configuration;
    private Dictionary<string, SchemaMetadata> _schemaMetadata = new();

    public ContractGenerator(GeneratorConfiguration configuration)
    {
        _configuration = configuration;
    }

    #region Schema Metadata

    /// <summary>
    /// Metadata about a schema's role in the inheritance hierarchy.
    /// </summary>
    private sealed class SchemaMetadata
    {
        /// <summary>True if the schema is a oneOf + discriminator pattern (Règle 1).</summary>
        public bool IsOneOfDiscriminated { get; set; }

        /// <summary>The discriminator property name (e.g. "type").</summary>
        public string? DiscriminatorPropertyName { get; set; }

        /// <summary>Mapping of discriminant value → schema name (e.g. "text" → "CreateTextCategoryAttributeRequest").</summary>
        public Dictionary<string, string> DerivedTypeMapping { get; set; } = new();

        /// <summary>The common allOf $ref base shared by all derived types (e.g. "CategoryAttributeCreateBase").</summary>
        public string? CommonAllOfBaseName { get; set; }

        /// <summary>True if the schema is an allOf with $ref + inline fragment (Règle 2).</summary>
        public bool IsAllOfInherited { get; set; }

        /// <summary>The $ref parent schema name from allOf.</summary>
        public string? AllOfParentName { get; set; }

        /// <summary>The resolved parent for C# inheritance (the oneOf root that references this type, if any).</summary>
        public string? ResolvedParentName { get; set; }

        /// <summary>True if the inline fragment has additionalProperties: false → sealed.</summary>
        public bool IsSealed { get; set; }

        /// <summary>Properties to skip because they are discriminant markers (Règle 5).</summary>
        public HashSet<string> DiscriminatorPropertiesToSkip { get; set; } = new();
    }

    #endregion

    #region Public Methods

    /// <summary>
    /// Generates contract code from an OpenAPI document and writes files to disk.
    /// </summary>
    /// <param name="document">The OpenAPI document containing schemas.</param>
    /// <returns>Paths of the generated files.</returns>
    public IEnumerable<string> Generate(OpenApiDocument document)
    {
        if (document.Components?.Schemas == null || document.Components.Schemas.Count == 0)
        {
            yield break;
        }

        // Pre-analysis pass: build metadata for all schemas
        _schemaMetadata = AnalyzeSchemas(document.Components.Schemas);

        foreach (var schema in document.Components.Schemas)
        {
            var sb = new StringBuilder();
            _schemaMetadata.TryGetValue(schema.Key, out var metadata);
            var needsStjUsing = metadata?.IsOneOfDiscriminated == true;

            AppendFileHeader(sb);
            AppendUsings(sb, needsStjUsing);
            AppendNamespace(sb);

            if (IsEnumSchema(schema.Value))
            {
                GenerateEnum(sb, schema.Key, schema.Value);
            }
            else
            {
                GenerateSchema(sb, schema.Key, schema.Value, metadata);
            }

            var sanitizedName = SanitizeName(schema.Key);
            var filePath = Path.Combine(_configuration.OutputDirectory, $"{sanitizedName}.g.cs");
            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
            yield return filePath;
        }
    }

    #endregion

    #region File Structure Generation

    /// <summary>
    /// Appends the file header with auto-generated marker and nullable enable directive.
    /// </summary>
    private static void AppendFileHeader(StringBuilder sb)
    {
        sb.AppendLine(Constants.CodeGeneration.AutoGeneratedHeader);
        sb.AppendLine(Constants.CodeGeneration.NullableDirective);
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the required using statements.
    /// </summary>
    private void AppendUsings(StringBuilder sb, bool includeStjSerialization = false)
    {
        sb.AppendLine("using System;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Collections.Generic;");

        if (_configuration.GenerateValidationAttributes)
        {
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        }

        if (includeStjSerialization)
        {
            sb.AppendLine("using System.Text.Json.Serialization;");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Appends the namespace declaration.
    /// </summary>
    private void AppendNamespace(StringBuilder sb)
    {
        var fullNamespace = string.IsNullOrWhiteSpace(_configuration.BaseNamespace)
            ? _configuration.ContractsNamespace
            : $"{_configuration.BaseNamespace}.{_configuration.ContractsNamespace}";

        sb.AppendLine($"namespace {fullNamespace};");
        sb.AppendLine();
    }

    #endregion

    #region Schema Generation

    /// <summary>
    /// Determines if a schema represents an enum.
    /// </summary>
    private static bool IsEnumSchema(IOpenApiSchema schema)
    {
        return schema.Enum is { Count: > 0 } &&
               schema.Type?.HasFlag(JsonSchemaType.String) == true;
    }

    /// <summary>
    /// Generates an enum from a schema.
    /// </summary>
    private void GenerateEnum(StringBuilder sb, string enumName, IOpenApiSchema schema)
    {
        AppendSchemaDocumentation(sb, schema);
        sb.AppendLine($"[GeneratedCode(\"{Constants.CodeGeneration.GeneratedCodeTool}\", \"{Constants.CodeGeneration.GeneratedCodeVersion}\")]");
        sb.AppendLine($"public enum {SanitizeName(enumName)}");
        sb.AppendLine("{");

        var enumValues = schema.Enum?.ToList() ?? [];
        for (var i = 0; i < enumValues.Count; i++)
        {
            var value = enumValues[i].ToString();
            var isLast = i == enumValues.Count - 1;

            if (_configuration.GenerateXmlDocumentation && !string.IsNullOrWhiteSpace(value))
            {
                sb.AppendLine($"{Constants.CodeGeneration.Indent}/// <summary>");
                sb.AppendLine($"{Constants.CodeGeneration.Indent}/// {EscapeXmlComment(value)}");
                sb.AppendLine($"{Constants.CodeGeneration.Indent}/// </summary>");
            }

            var enumMemberName = SanitizeEnumMemberName(value);
            sb.AppendLine($"{Constants.CodeGeneration.Indent}{enumMemberName}{(isLast ? string.Empty : ",")}");
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Generates a single schema (class or record), dispatching to the appropriate generator
    /// based on the schema's role in the polymorphism hierarchy.
    /// </summary>
    private void GenerateSchema(StringBuilder sb, string schemaName, IOpenApiSchema schema, SchemaMetadata? metadata)
    {
        if (metadata?.IsOneOfDiscriminated == true)
        {
            GenerateAbstractDiscriminatedRecord(sb, schemaName, schema, metadata);
        }
        else if (metadata?.IsAllOfInherited == true)
        {
            GenerateConcreteInheritedRecord(sb, schemaName, schema, metadata);
        }
        else
        {
            GenerateStandardSchema(sb, schemaName, schema);
        }
    }

    /// <summary>
    /// Generates a standard schema (class or record) with no polymorphism.
    /// </summary>
    private void GenerateStandardSchema(StringBuilder sb, string schemaName, IOpenApiSchema schema)
    {
        AppendSchemaDocumentation(sb, schema);
        AppendSchemaDeclaration(sb, schemaName);
        AppendSchemaProperties(sb, schema);
        sb.AppendLine("}");
    }

    /// <summary>
    /// Generates an abstract record with [JsonPolymorphic] and [JsonDerivedType] attributes (Règle 1).
    /// </summary>
    private void GenerateAbstractDiscriminatedRecord(StringBuilder sb, string schemaName, IOpenApiSchema schema, SchemaMetadata metadata)
    {
        AppendSchemaDocumentation(sb, schema);

        // [JsonPolymorphic] attribute
        sb.AppendLine($"[JsonPolymorphic(TypeDiscriminatorPropertyName = \"{metadata.DiscriminatorPropertyName}\")]");

        // [JsonDerivedType] for each mapping entry
        foreach (var entry in metadata.DerivedTypeMapping)
        {
            var derivedTypeName = SanitizeName(entry.Value);
            sb.AppendLine($"[JsonDerivedType(typeof({derivedTypeName}), \"{entry.Key}\")]");
        }

        sb.AppendLine($"[GeneratedCode(\"{Constants.CodeGeneration.GeneratedCodeTool}\", \"{Constants.CodeGeneration.GeneratedCodeVersion}\")]");
        var keyword = _configuration.UseRecords ? "record" : "class";
        var baseSuffix = metadata.CommonAllOfBaseName != null
            ? $" : {SanitizeName(metadata.CommonAllOfBaseName)}"
            : string.Empty;
        sb.AppendLine($"public abstract {keyword} {SanitizeName(schemaName)}{baseSuffix};");
    }

    /// <summary>
    /// Generates a concrete record inheriting from the abstract discriminated type (Règle 2).
    /// Only properties from the inline fragment are generated; inherited properties come from the parent.
    /// The discriminant property (Règle 5) is excluded.
    /// </summary>
    private void GenerateConcreteInheritedRecord(StringBuilder sb, string schemaName, IOpenApiSchema schema, SchemaMetadata metadata)
    {
        var parentName = metadata.ResolvedParentName ?? metadata.AllOfParentName;
        var sealedModifier = metadata.IsSealed ? "sealed " : string.Empty;
        var keyword = _configuration.UseRecords ? "record" : "class";

        AppendSchemaDocumentation(sb, schema);
        sb.AppendLine($"[GeneratedCode(\"{Constants.CodeGeneration.GeneratedCodeTool}\", \"{Constants.CodeGeneration.GeneratedCodeVersion}\")]");

        var parentSuffix = parentName != null ? $" : {SanitizeName(parentName)}" : string.Empty;
        sb.AppendLine($"public {sealedModifier}{keyword} {SanitizeName(schemaName)}{parentSuffix}");
        sb.AppendLine("{");

        // Get the inline fragment and generate only its properties
        var inlineFragment = TypeUtils.GetAllOfInlineFragment(schema);
        if (inlineFragment?.Properties != null)
        {
            foreach (var property in inlineFragment.Properties)
            {
                // Skip discriminant properties (Règle 5)
                if (metadata.DiscriminatorPropertiesToSkip.Contains(property.Key))
                {
                    continue;
                }

                var isRequired = inlineFragment.Required?.Contains(property.Key) ?? false;
                GenerateProperty(sb, property.Key, property.Value, isRequired);
            }
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Appends XML documentation for a schema.
    /// </summary>
    private void AppendSchemaDocumentation(StringBuilder sb, IOpenApiSchema schema)
    {
        if (!_configuration.GenerateXmlDocumentation || string.IsNullOrWhiteSpace(schema.Description))
        {
            return;
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {EscapeXmlComment(schema.Description)}");
        sb.AppendLine("/// </summary>");
    }

    /// <summary>
    /// Appends the schema declaration (class or record) for a standard schema.
    /// </summary>
    private void AppendSchemaDeclaration(StringBuilder sb, string schemaName)
    {
        sb.AppendLine($"[GeneratedCode(\"{Constants.CodeGeneration.GeneratedCodeTool}\", \"{Constants.CodeGeneration.GeneratedCodeVersion}\")]");
        var keyword = _configuration.UseRecords ? "record" : "class";
        sb.AppendLine($"public {keyword} {SanitizeName(schemaName)}()");
        sb.AppendLine("{");
    }

    /// <summary>
    /// Appends all properties of a schema.
    /// </summary>
    private void AppendSchemaProperties(StringBuilder sb, IOpenApiSchema schema)
    {
        if (schema.Properties == null)
        {
            return;
        }

        foreach (var property in schema.Properties)
        {
            var isRequired = schema.Required?.Contains(property.Key) ?? false;
            GenerateProperty(sb, property.Key, property.Value, isRequired);
        }
    }

    /// <summary>
    /// Generates a single property with documentation and validation attributes.
    /// </summary>
    private void GenerateProperty(StringBuilder sb, string propertyName, IOpenApiSchema propertySchema, bool isRequired)
    {
        AppendPropertyDocumentation(sb, propertySchema);
        AppendValidationAttributes(sb, propertySchema, isRequired);
        AppendPropertyDeclaration(sb, propertyName, propertySchema, isRequired);
    }

    #endregion

    #region Documentation and Attributes

    /// <summary>
    /// Appends XML documentation for a property.
    /// </summary>
    private void AppendPropertyDocumentation(StringBuilder sb, IOpenApiSchema propertySchema)
    {
        if (!_configuration.GenerateXmlDocumentation || string.IsNullOrWhiteSpace(propertySchema.Description))
        {
            return;
        }

        sb.AppendLine($"{Constants.CodeGeneration.Indent}/// <summary>");
        sb.AppendLine($"{Constants.CodeGeneration.Indent}/// {EscapeXmlComment(propertySchema.Description)}");
        sb.AppendLine($"{Constants.CodeGeneration.Indent}/// </summary>");
    }

    /// <summary>
    /// Appends validation attributes for a property.
    /// </summary>
    private void AppendValidationAttributes(StringBuilder sb, IOpenApiSchema propertySchema, bool isRequired)
    {
        if (!_configuration.GenerateValidationAttributes)
        {
            return;
        }

        if (isRequired)
        {
            sb.AppendLine($"{Constants.CodeGeneration.Indent}[Required]");
        }

        AppendStringLengthAttribute(sb, propertySchema);
        AppendRangeAttribute(sb, propertySchema);
        AppendPatternAttribute(sb, propertySchema);
    }

    /// <summary>
    /// Appends the StringLength validation attribute if applicable.
    /// </summary>
    private static void AppendStringLengthAttribute(StringBuilder sb, IOpenApiSchema propertySchema)
    {
        if (!propertySchema.MinLength.HasValue && !propertySchema.MaxLength.HasValue)
        {
            return;
        }

        var min = propertySchema.MinLength ?? 0;
        var max = propertySchema.MaxLength?.ToString() ?? "int.MaxValue";
        sb.AppendLine($"{Constants.CodeGeneration.Indent}[StringLength({max}, MinimumLength = {min})]");
    }

    /// <summary>
    /// Appends the Range validation attribute if applicable.
    /// </summary>
    private static void AppendRangeAttribute(StringBuilder sb, IOpenApiSchema propertySchema)
    {
        if (propertySchema.Minimum is null && propertySchema.Maximum is null)
        {
            return;
        }

        var min = propertySchema.Minimum is not null ? $"{propertySchema.Minimum}" : "double.MinValue";
        var max = propertySchema.Maximum is not null ? $"{propertySchema.Maximum}" : "double.MaxValue";
        sb.AppendLine($"{Constants.CodeGeneration.Indent}[Range({min}, {max})]");
    }

    /// <summary>
    /// Appends the RegularExpression validation attribute if applicable.
    /// </summary>
    private static void AppendPatternAttribute(StringBuilder sb, IOpenApiSchema propertySchema)
    {
        if (propertySchema.Pattern == null)
        {
            return;
        }

        // Escape double quotes in the pattern for C# verbatim string
        var escapedPattern = propertySchema.Pattern.Replace("\"", "\"\"");
        sb.AppendLine($"{Constants.CodeGeneration.Indent}[RegularExpression(@\"{escapedPattern}\")]");
    }

    /// <summary>
    /// Appends the property declaration.
    /// </summary>
    private static void AppendPropertyDeclaration(StringBuilder sb, string propertyName, IOpenApiSchema propertySchema, bool isRequired)
    {
        var csharpType = TypeUtils.DetermineFinalType(propertySchema);

        // If the property is not required and not already nullable, make it nullable
        if (!isRequired && !TypeUtils.IsNullableType(propertySchema) && !csharpType.EndsWith("?"))
        {
            csharpType += "?";
        }

        var sanitizedName = SanitizeName(propertyName, pascalCase: true);
        var requiredModifier = isRequired ? "required " : string.Empty;

        sb.AppendLine($"{Constants.CodeGeneration.Indent}public {requiredModifier}{csharpType} {sanitizedName} {{ get; set; }}");
    }

    #endregion

    #region Schema Analysis

    /// <summary>
    /// Analyzes all schemas to build metadata for polymorphism support.
    /// </summary>
    private static Dictionary<string, SchemaMetadata> AnalyzeSchemas(
        IDictionary<string, IOpenApiSchema> schemas)
    {
        var metadata = new Dictionary<string, SchemaMetadata>();

        // First pass: identify oneOf+discriminator schemas and allOf-inherited schemas
        foreach (var schemaEntry in schemas)
        {
            var name = schemaEntry.Key;
            var schema = schemaEntry.Value;
            var meta = new SchemaMetadata();

            if (schema.Discriminator is not null && TypeUtils.IsOneOfDiscriminated(schema))
            {
                meta.IsOneOfDiscriminated = true;
                meta.DiscriminatorPropertyName = schema.Discriminator.PropertyName;
                meta.DerivedTypeMapping = BuildDerivedTypeMapping(schema);
            }
            else if (TypeUtils.IsAllOfInherited(schema))
            {
                meta.IsAllOfInherited = true;
                meta.AllOfParentName = TypeUtils.GetAllOfParentRefName(schema);

                // Check if sealed (additionalProperties: false on inline fragment)
                var inline = TypeUtils.GetAllOfInlineFragment(schema);
                if (inline?.AdditionalProperties != null)
                {
                    // In OpenAPI 3.1, additionalProperties can be a schema or a boolean.
                    // When it's `false`, the library may represent it differently.
                    // We check AdditionalPropertiesAllowed for the boolean case.
                    meta.IsSealed = !schema.AdditionalPropertiesAllowed;
                }
                else if (inline != null)
                {
                    // Also check the inline fragment directly
                    meta.IsSealed = !inline.AdditionalPropertiesAllowed;
                }
            }

            metadata[name] = meta;
        }

        // Second pass: resolve parent references for allOf schemas
        // If a concrete type is listed in a oneOf's entries, its C# parent is the oneOf abstract type
        var oneOfParentMap = BuildOneOfParentMap(metadata);

        foreach (var metaEntry in metadata)
        {
            var name = metaEntry.Key;
            var meta = metaEntry.Value;

            if (!meta.IsAllOfInherited)
            {
                continue;
            }

            // Check if this schema is referenced by a oneOf+discriminator schema
            if (oneOfParentMap.TryGetValue(name, out var oneOfParentName))
            {
                meta.ResolvedParentName = oneOfParentName;
            }
            else
            {
                // Otherwise, inherit from the allOf $ref parent
                meta.ResolvedParentName = meta.AllOfParentName;
            }

            // Identify discriminant properties to skip (Règle 5)
            var parentOneOfName = meta.ResolvedParentName;
            if (parentOneOfName != null && metadata.TryGetValue(parentOneOfName, out var parentMeta)
                                        && parentMeta.IsOneOfDiscriminated
                                        && parentMeta.DiscriminatorPropertyName != null)
            {
                var inline = schemas.TryGetValue(name, out var s) ? TypeUtils.GetAllOfInlineFragment(s) : null;
                if (inline?.Properties != null)
                {
                    var discriminatorPropName = parentMeta.DiscriminatorPropertyName;
                    if (inline.Properties.TryGetValue(discriminatorPropName, out var propSchema))
                    {
                        // It's a discriminant property if it has an enum with exactly one value
                        if (propSchema.Enum is { Count: 1 })
                        {
                            meta.DiscriminatorPropertiesToSkip.Add(discriminatorPropName);
                        }
                    }
                }
            }
        }

        // Third pass: resolve common allOf base for oneOf+discriminator schemas
        // If all derived types share the same allOf $ref base, the abstract record inherits from it
        foreach (var metaEntry in metadata)
        {
            var meta = metaEntry.Value;
            if (!meta.IsOneOfDiscriminated || meta.DerivedTypeMapping.Count == 0)
            {
                continue;
            }

            string? commonBase = null;
            var allShareSameBase = true;

            foreach (var derivedName in meta.DerivedTypeMapping.Values)
            {
                if (!metadata.TryGetValue(derivedName, out var derivedMeta) || !derivedMeta.IsAllOfInherited)
                {
                    allShareSameBase = false;
                    break;
                }

                if (commonBase == null)
                {
                    commonBase = derivedMeta.AllOfParentName;
                }
                else if (commonBase != derivedMeta.AllOfParentName)
                {
                    allShareSameBase = false;
                    break;
                }
            }

            if (allShareSameBase && commonBase != null)
            {
                meta.CommonAllOfBaseName = commonBase;
            }
        }

        return metadata;
    }

    /// <summary>
    /// Builds the derived type mapping from a oneOf+discriminator schema.
    /// Uses discriminator.mapping if present, otherwise infers from $ref names.
    /// </summary>
    private static Dictionary<string, string> BuildDerivedTypeMapping(IOpenApiSchema schema)
    {
        var mapping = new Dictionary<string, string>();

        if (schema.Discriminator?.Mapping is { Count: > 0 } explicitMapping)
        {
            foreach (var entry in explicitMapping)
            {
                // Mapping value is an OpenApiSchemaReference — extract the reference ID
                var refName = entry.Value?.Reference.Id ?? entry.Key;
                mapping[entry.Key] = refName;
            }
        }
        else if (schema.OneOf != null)
        {
            // Fallback: infer discriminant values from $ref names
            foreach (var oneOfEntry in schema.OneOf)
            {
                if (oneOfEntry is OpenApiSchemaReference { Reference.Id: not null } refSchema)
                {
                    // Use the lowercase schema name as discriminant value
                    var name = refSchema.Reference.Id;
                    mapping[name.ToLowerInvariant()] = name;
                }
            }
        }

        return mapping;
    }

    /// <summary>
    /// Builds a map from derived schema name → oneOf parent schema name.
    /// This allows resolving which abstract type a concrete type should inherit from.
    /// </summary>
    private static Dictionary<string, string> BuildOneOfParentMap(Dictionary<string, SchemaMetadata> metadata)
    {
        var map = new Dictionary<string, string>();

        foreach (var metaEntry in metadata)
        {
            var parentName = metaEntry.Key;
            var meta = metaEntry.Value;

            if (!meta.IsOneOfDiscriminated)
            {
                continue;
            }

            foreach (var derivedName in meta.DerivedTypeMapping.Values)
            {
                map[derivedName] = parentName;
            }
        }

        return map;
    }

    #endregion

    #region Helper Methods

    /// <summary>
    /// Sanitizes a name to be a valid C# identifier, optionally converting to PascalCase.
    /// </summary>
    private static string SanitizeName(string name, bool pascalCase = false)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return "UnnamedProperty";
        }

        var sanitized = new StringBuilder();
        var nextUpper = pascalCase;

        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c))
            {
                sanitized.Append(nextUpper ? char.ToUpper(c) : c);
                nextUpper = false;
            }
            else if (c is '_' or '-' or '.' or ' ')
            {
                nextUpper = true;
            }
        }

        var result = sanitized.ToString();

        // Ensure the name starts with a letter
        if (result.Length == 0 || !char.IsLetter(result[0]))
        {
            result = "Property" + result;
        }

        return result;
    }

    /// <summary>
    /// Sanitizes an enum member name to be a valid C# identifier in PascalCase.
    /// </summary>
    private static string SanitizeEnumMemberName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return "Unknown";
        }

        var sanitized = new StringBuilder();
        var nextUpper = true;

        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c))
            {
                sanitized.Append(nextUpper ? char.ToUpper(c) : c);
                nextUpper = false;
            }
            else if (c is '_' or '-' or '.' or ' ')
            {
                nextUpper = true;
            }
        }

        var result = sanitized.ToString();

        // Ensure the name starts with a letter
        if (result.Length == 0 || !char.IsLetter(result[0]))
        {
            result = "Value" + result;
        }

        return result;
    }

    /// <summary>
    /// Escapes special XML characters in a comment.
    /// </summary>
    private static string EscapeXmlComment(string? comment)
    {
        if (comment == null)
        {
            return string.Empty;
        }

        return comment
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;");
    }

    #endregion
}
