namespace TeknixIT.OpenApiGenerator.Server;

/// <summary>
/// Constants used throughout the generator.
/// </summary>
internal static class Constants
{
    /// <summary>
    /// Default values for configuration.
    /// </summary>
    public static class Defaults
    {
        public const string BaseNamespace = "Generated";
        public const string ContractsNamespace = "Contracts";
        public const string ControllersNamespace = "Controllers";
        public const string ControllerBaseClass = "ControllerBase";
    }

    /// <summary>
    /// Code generation constants.
    /// </summary>
    public static class CodeGeneration
    {
        public const string AutoGeneratedHeader = "// <auto-generated />";
        public const string NullableDirective = "#nullable enable";
        public const string Indent = "    ";
        public const string GeneratedCodeTool = "TeknixIT.OpenApiGenerator.Server";
        public static readonly string GeneratedCodeVersion =
            typeof(Constants).Assembly.GetName().Version?.ToString(3) ?? "0.0.0";
    }
}
